name: Build and deploy Python app to Azure Web App - Sanctionschecker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Match the Python version to your development environment

      - name: Install Python and PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8  # Optional: Ensures your code base follows PEP8 standards
        run: |
          pip install flake8
          flake8 --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with pytest  # Optional: Run tests to ensure app is working as expected
        run: |
          pip install pytest
          pytest

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*venv*" -x "*.git*"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Sanctionschecker'
          slot-name: 'production'  # Ensure the slot name is set correctly if using slots
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_590546FBCC564A39BFFA4F4DB1AD41E1 }}

